
fortune_list = [ "A beautiful, smart, and loving person will be coming into your life.",
            "A dubious friend may be an enemy in camouflage.",
            "A faithful friend is a strong defense.",
            "A feather in the hand is better than a bird in the air. (2)",
            "A fresh start will put you on your way.",
            "A friend asks only for your time not your money.",
            "A friend is a present you give yourself.",
            "A gambler not only will lose what he has, but also will lose what he doesn’t have.",
            "A golden egg of opportunity falls into your lap this month.",
            "A good friendship is often more important than a passionate romance.",
            "A good time to finish up old tasks. (2)",
            "A hunch is creativity trying to tell you something.",
            "A lifetime friend shall soon be made.",
            "A lifetime of happiness lies ahead of you.",
            "A light heart carries you through all the hard times.",
            "A new outlook brightens your image and brings new friends.",
            "A new perspective will come with the new year. (2)",
            "A person is never to (sic) old to learn. (2)",
            "A person of words and not deeds is like a garden full of weeds.",
            "A pleasant surprise is waiting for you.",
            "A short pencil is usually better than a long memory any day.",
            "A small donation is call for. It’s the right thing to do.",
            "A smile is your personal welcome mat.",
            "A smooth long journey! Great expectations.",
            "A soft voice may be awfully persuasive.",
            "A truly rich life contains love and art in abundance.",
            "Accept something that you cannot change, and you will feel better.",
            "Adventure can be real happiness.",
            "Advice is like kissing. It costs nothing and is a pleasant thing to do. (2)",
            "Advice, when most needed, is least heeded.",
            "All the effort you are making will ultimately pay off.",
            "All the troubles you have will pass away very quickly.",
            "All will go well with your new project.",
            "All your hard work will soon pay off.",
            "Allow compassion to guide your decisions.",
            "An acquaintance of the past will affect you in the near future.",
            "An agreeable romance might begin to take on the appearance.",
            "An important person will offer you support.",
            "An inch of time is an inch of gold.",
            "Any day above ground is a good day.",
            "Any decision you have to make tomorrow is a good decision.",
            "At the touch of love, everyone becomes a poet.",
            "Be careful or you could fall for some tricks today.",
            "Beauty in its various forms appeals to you. (2)",
            "Because you demand more from yourself, others respect you deeply.",
            "Believe in yourself and others will too.",
            "Believe it can be done.",
            "Better ask twice than lose yourself once.",
            "Bide your time, for success is near.",
            "Carve your name on your heart and not on marble.",
            "Chance favors those in motion.",
            "Change is happening in your life, so go with the flow!",
            "Competence like yours is underrated.",
            "Congratulations! You are on your way.",
            "Could I get some directions to your heart? (2)",
            "Courtesy begins in the home.",
            "Courtesy is contagious.",
            "Curiosity kills boredom. Nothing can kill curiosity.",
            "Dedicate yourself with a calm mind to the task at hand.",
            "Depart not from the path which fate has you assigned.",
            "Determination is what you need now.",
            "Diligence and modesty can raise your social status.",
            "Disbelief destroys the magic.",
            "Distance yourself from the vain.",
            "Do not be intimidated by the eloquence of others.",
            "Do not demand for someone’s soul if you already got his heart.",
            "Do not let ambitions overshadow small success.",
            "Do not make extra work for yourself.",
            "Do not underestimate yourself. Human beings have unlimited potentials.",
            "Do you know that the busiest person has the largest amount of time?",
                 "You have an active mind and a keen imagination.",
                 "You have an ambitious nature and may make a name for yourself.",
                 "You have an unusual equipment for success, use it properly.",
                 "You have exceeded what was expected.",
                 "You have had a good start. Work harder!",
                 "You have the power to write your own fortune.",
                 "You have yearning for perfection.",
                 "You know where you are going and how to get there.",
                 "You look pretty.",
                 "You love challenge.",
                 "You love chinese food.",
                 "You make people realize that there exist other beauties in the world.",
                 "You never hesitate to tackle the most difficult problems. (2)",
                 "You never know who you touch.",
                 "You only treasure what you lost.",
                 "You seek to shield those you love and like the role of provider. (2)",
                 "You should be able to make money and hold on to it.",
                 "You should be able to undertake and complete anything.",
                 "You should pay for this check. Be generous.",
                 "You understand how to have fun with others and to enjoy your solitude.",
                 "You will always be surrounded by true friends.",
                 "You will always get what you want through your charm and personality.",
                 "You will always have good luck in your personal affairs.",
                 "You will be a great success both in the business world and society. (2)",
                 "You will be blessed with longevity.",
                 "You will be pleasantly surprised tonight.",
                 "You will be sharing great news with all the people you love.",
                 "You will be successful in your work.",
                 "You will be traveling and coming into a fortune.",
                 "You will be unusually successful in business.",
                 "You will become a great philanthropist in your later years.",
                 "You will become more and more wealthy.",
                 "You will enjoy good health.",
                 "You will enjoy good health; you will be surrounded by luxury.",
                 "You will find great contentment in the daily, routine activities.",
                 "You will have a fine capacity for the enjoyment of life.",
                 "You will have gold pieces by the bushel.",
                 "You will inherit a large sum of money.",
                 "You will make change for the better.",
                 "You will soon be surrounded by good friends and laughter.",
                 "You will take a chance in something in near future.",
                 "You will travel far and wide, both pleasure and business.",
                 "You will travel far and wide,both pleasure and business.",
                 "Your abilities are unparalleled.",
                 "Your ability is appreciated.",
                 "Your ability to juggle many tasks will take you far.",
                 "Your biggest virtue is your modesty.",
                 "Your character can be described as natural and unrestrained.",
                 "Your difficulties will strengthen you.",
                 "Your dreams are never silly; depend on them to guide you.",
                 "Your dreams are worth your best efforts to achieve them.",
                 "Your energy returns and you get things done.",
                 "Your family is young, gifted and attractive.",
                 "Your first love has never forgotten you.",
                 "Your goal will be reached very soon.",
                 "Your happiness is before you, not behind you! Cherish it.",
                 "Your hard work will payoff today.",
                 "Your heart will always make itself known through your words.",
                 "Your home is the center of great love.",
                 "Your ideals are well within your reach.",
                 "Your infinite capacity for patience will be rewarded sooner or later.",
                 "Your leadership qualities will be tested and proven.",
                 "Your life will be happy and peaceful.",
                 "Your life will get more and more exciting.",
                 "Your love life will be happy and harmonious.",
                 "Your love of music will be an important part of your life.",
                 "Your loyalty is a virtue, but not when it’s wedded with blind stubbornness.",
                 "Your mentality is alert, practical, and analytical.",
                 "Your mind is creative, original and alert.",
                 "Your mind is your greatest asset.",
                 "Your moods signal a period of change.",
                 "Your quick wits will get you out of a tough situation.",
                 "Your reputation is your wealth.",
                 "Your success will astonish everyone. (2)",
                 "Your talents will be recognized and suitably rewarded.",
                 "Your work interests can capture the highest status or prestige."
                 ]